"""
Evaluate previously generated edits with configurable scorers.

This script reads edits from a JSONL file (generated by generate_edits.py) and
evaluates them with different scorer configurations. This allows you to test
which scorers are most important without regenerating edits.

All scorer thresholds are defined in the scorer classes themselves.

Usage:
    # Evaluate with all scorers enabled
    python models/evaluate_edits.py --input_jsonl <input_file.jsonl> --output_jsonl <output_file.jsonl>

    # Evaluate with specific scorers disabled (ablation study)
    python models/evaluate_edits.py --input_jsonl <input_file.jsonl> --output_jsonl <output_file.jsonl> \
        --disable_human_like --disable_fluency

    # Enable Weave tracing for monitoring calculations
    python models/evaluate_edits.py --input_jsonl <input_file.jsonl> --output_jsonl <output_file.jsonl> \
        --weave_project username/project-name
"""

import os
import sys
import time
import logging
import json
import re
from typing import List, Dict, Any, Optional
import argparse
from pathlib import Path

# Add project root to path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

import torch
import numpy as np
import weave

from scorers.local_scorers.fluency.fluency_scorer import FluencyScorer
from scorers.appropriateness.appropriateness_scorer import AppropriatenessScorer
from scorers.local_scorers.semantic_similarity.semantic_similarity_scorer import SemanticSimilarityScorer
from scorers.local_scorers.human_like.human_like_scorer import HumanLikeScorer
from scorers.global_scorers.semantic_similarity.global_semantic_similarity_scorer import GlobalSemanticSimilarityScorer
from scorers.global_scorers.human_like.global_human_like_scorer_v2 import GlobalHumanLikeScorerV2
from scorers.global_scorers.fluency.global_fluency_scorer import GlobalFluencyScorer
from ops.edit_applier import apply_edits_to_argument

# Import MetricsCalculator for computing App, Sim, NES, PPL
sys.path.insert(0, str(project_root / 'models' / 'ppo_metrics'))
from calculate_metrics import MetricsCalculator

# -----------------------------
# Logging
# -----------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
)
logger = logging.getLogger(__name__)

# Analysis dimensions
_ANALYSIS_DIMS = [
    "Inappropriateness",
    "Toxic Emotions",
    "Missing Commitment",
    "Missing Intelligibility",
    "Other Reasons",
]


# -----------------------------
# Helper functions
# -----------------------------


def _group_edits_by_sentence(edits: List[Dict[str, Any]]) -> Dict[str, List[Dict[str, str]]]:
    """
    Group edits by their original sentence.

    Args:
        edits: List of edits with 'original_sentence', 'inappropriate_part', 'rewritten_part'

    Returns:
        Dict mapping sentence text to list of edits in that sentence
    """
    edits_by_sentence = {}

    for edit in edits:
        original_sentence = edit.get('original_sentence', '')
        if not original_sentence:
            continue

        if original_sentence not in edits_by_sentence:
            edits_by_sentence[original_sentence] = []

        edits_by_sentence[original_sentence].append({
            'inappropriate_part': edit.get('inappropriate_part'),
            'rewritten_part': edit.get('rewritten_part')
        })

    return edits_by_sentence


# -----------------------------
# Reward computation per edit
# -----------------------------
@weave.op()
def score_edit(
    original_argument: str,
    edit: Dict[str, Any],
    baseline_scores: Dict[str, float] | None,
    original_sentence_context: Optional[str],
    semantic_similarity_scorer,
    fluency_scorer,
    human_like_scorer,
    appropriateness_scorer
) -> Dict[str, Any]:
    """Score a single edit with the provided scorers."""
    reason = edit.get("reason")
    inappropriate_part = edit.get("inappropriate_part")
    rewritten_part = edit.get("rewritten_part")

    # Validity check
    edit_context = original_sentence_context if original_sentence_context is not None else original_argument
    has_reason = bool(reason)
    has_at_least_one = bool(inappropriate_part) or bool(rewritten_part)
    substring_match = (not inappropriate_part) or (inappropriate_part in edit_context)
    is_well_formed = has_reason and has_at_least_one and substring_match

    logger.info(f"Scoring edit: inappropriate_part='{inappropriate_part}', rewritten_part='{rewritten_part}', reason='{reason}'")
    logger.info(f"is_well_formed: {is_well_formed} (reason={has_reason}, has_content={has_at_least_one}, substring_match={substring_match})")

    semantic_similarity = 0.0
    fluency_score = 0.0
    human_like = 0.0
    app_reward = 0.0
    reason_correct = False
    reason_correct_relaxed = False
    classifier_true_reason = None

    if is_well_formed:
        # Semantic similarity
        if semantic_similarity_scorer:
            try:
                context = original_sentence_context if original_sentence_context is not None else original_argument
                semantic_similarity, ss_score = semantic_similarity_scorer.calculate_semantic_similarity(
                    context, inappropriate_part, rewritten_part
                )
                logger.info(f"Semantic similarity: binary={semantic_similarity}, score={ss_score}")
            except Exception as e:
                semantic_similarity = 0.0
                logger.error(f"Semantic similarity check failed: {e}")

        # Fluency
        if fluency_scorer:
            try:
                context = original_sentence_context if original_sentence_context is not None else original_argument
                fluency_score = fluency_scorer.calculate_fluency(context, inappropriate_part, rewritten_part)
                logger.info(f"Fluency Output: {fluency_score}")
            except Exception as e:
                fluency_score = 0.0
                logger.error(f"Fluency check failed: {e}")

        # Human-like
        if human_like_scorer:
            try:
                context = original_sentence_context if original_sentence_context is not None else original_argument
                human_like = human_like_scorer.calculate_human_likeness(
                    original_argument, context, inappropriate_part, rewritten_part
                )
                logger.info(f"Human-like score: {human_like}")
            except Exception as e:
                human_like = 0.0
                logger.error(f"Human-like check failed: {e}")

        # Edit-level appropriateness classifier reward
        if appropriateness_scorer:
            try:
                if original_sentence_context and inappropriate_part in original_sentence_context:
                    modified_sentence = original_sentence_context.replace(inappropriate_part, rewritten_part, 1)
                    modified_argument = original_argument.replace(original_sentence_context, modified_sentence, 1)
                else:
                    modified_argument = original_argument.replace(inappropriate_part, rewritten_part, 1)
                before_scores = baseline_scores if baseline_scores is not None else appropriateness_scorer.get_appropriateness_scores(original_argument)
                after_scores = appropriateness_scorer.get_appropriateness_scores(modified_argument)

                # Compute improvement for overall inappropriateness
                dim_before = before_scores.get("Inappropriateness")
                dim_after = after_scores.get("Inappropriateness")
                if dim_before is not None and dim_after is not None:
                    app_reward = 1.0 if (dim_after < dim_before) else 0.0

                # Evaluate reason correctness
                dimension_improvements = {}
                for dim in _ANALYSIS_DIMS[1:]:
                    dim_before_val = before_scores.get(dim)
                    dim_after_val = after_scores.get(dim)
                    if dim_before_val is not None and dim_after_val is not None:
                        improvement = dim_before_val - dim_after_val
                        dimension_improvements[dim] = improvement

                positive_improvements = {
                    dim: imp for dim, imp in dimension_improvements.items() if imp > 0
                }

                if positive_improvements:
                    classifier_true_reason = max(positive_improvements, key=positive_improvements.get)
                    reason_correct = (reason == classifier_true_reason)
                    # Relaxed version: correct if predicted dimension improved at all (not necessarily max)
                    reason_correct_relaxed = (reason in positive_improvements)
                    logger.info(f"Reason evaluation: predicted='{reason}', true='{classifier_true_reason}', correct={reason_correct}, correct_relaxed={reason_correct_relaxed}")

            except Exception as e:
                app_reward = 0.0
                reason_correct = False
                reason_correct_relaxed = False
                classifier_true_reason = None
                logger.error(f"App reward check failed: {e}")

    # Perfect reward: semantic similarity, fluency, and human-like must all pass
    enabled_scores = []
    if semantic_similarity_scorer:
        enabled_scores.append(semantic_similarity)
    if fluency_scorer:
        enabled_scores.append(fluency_score)
    if human_like_scorer:
        enabled_scores.append(human_like)

    perfect = 1.0 if (is_well_formed and all(s == 1.0 for s in enabled_scores) and enabled_scores) else 0.0
    logger.info(f"Perfect score: {perfect} (based on: semantic_similarity={semantic_similarity}, fluency={fluency_score}, human_like={human_like})")

    return {
        "reason": reason,
        "classifier_true_reason": classifier_true_reason,
        "inappropriate_part": inappropriate_part,
        "rewritten_part": rewritten_part,
        "valid": bool(is_well_formed),
        "reason_correct": bool(reason_correct),
        "reason_correct_relaxed": bool(reason_correct_relaxed),
        "rewards": {
            "semantic_similarity": float(semantic_similarity),
            "fluency": float(fluency_score),
            "human_like": float(human_like),
            "app": float(app_reward),
            "perfect": float(perfect),
        },
    }


@weave.op()
def main(
    input_jsonl: str,
    output_jsonl: str,
    disable_semantic_similarity: bool = False,
    disable_fluency: bool = False,
    disable_human_like: bool = False,
    disable_appropriateness: bool = False,
    weave_project: str = None,
):
    """Evaluate edits from input JSONL and save scored results to output JSONL."""
    # Initialize weave if project name is provided
    if weave_project:
        weave.init(weave_project)
        logger.info(f"Initialized Weave with project: {weave_project}")

    os.makedirs(os.path.dirname(output_jsonl), exist_ok=True)

    logger.info(f"Starting evaluation. Input: {input_jsonl}, Output: {output_jsonl}")

    # Initialize scorers based on configuration
    _cuda_available = torch.cuda.is_available()
    _local_rank = int(os.environ.get("LOCAL_RANK", 0)) if _cuda_available else 0
    _device = torch.device(f"cuda:{_local_rank}" if _cuda_available else "cpu")

    logger.info("Loading scorers (using default thresholds from scorer classes)...")
    # All scorers use their default thresholds defined in the class __init__
    semantic_similarity_scorer = None if disable_semantic_similarity else SemanticSimilarityScorer(_device)
    human_like_scorer = None if disable_human_like else HumanLikeScorer(_device)
    fluency_scorer = None if disable_fluency else FluencyScorer(_device)
    appropriateness_scorer = None if disable_appropriateness else AppropriatenessScorer(_device)

    # Global scorers (use their default thresholds)
    logger.info("Loading global scorers...")
    global_semantic_similarity_scorer = GlobalSemanticSimilarityScorer(_device)
    global_human_like_scorer = GlobalHumanLikeScorerV2(_device)
    global_fluency_scorer = GlobalFluencyScorer(_device)

    # MetricsCalculator for computing App, Sim, NES, PPL
    logger.info("Loading MetricsCalculator for App, Sim, NES, PPL metrics...")
    metrics_calculator = MetricsCalculator(
        semantic_similarity=True,
        token_edit_distance=True,
        perplexity=True,
        classifier_prediction=True,  # Enable appropriateness classifier
        batch_size=1,
        classifier_fold=0,
        device=_device
    )

    # Aggregate metrics
    num_examples = 0
    total_edits = 0
    total_valid_edits = 0
    total_perfect_reward_ones = 0
    total_reason_correct = 0
    total_reason_correct_relaxed = 0
    flips_per_dim: Dict[str, int] = {dim: 0 for dim in _ANALYSIS_DIMS}

    # Track invalid edit reasons
    invalid_reasons = {
        'no_reason': 0,
        'no_content': 0,
        'substring_mismatch': 0
    }

    # Track why valid edits fail to be perfect
    imperfect_reasons = {
        'semantic_similarity_failed': 0,
        'fluency_failed': 0,
        'human_like_failed': 0,
        'multiple_failed': 0
    }

    # Track total failures per scorer (including when failing with others)
    total_scorer_failures = {
        'semantic_similarity': 0,
        'fluency': 0,
        'human_like': 0
    }

    start_all = time.time()
    with open(input_jsonl, "r", encoding="utf-8") as f_in, open(output_jsonl, "w", encoding="utf-8") as f_out:
        for idx, line in enumerate(f_in):
            example_start = time.time()
            try:
                example = json.loads(line.strip())
            except json.JSONDecodeError as e:
                logger.error(f"Failed to parse line {idx}: {e}")
                continue

            num_examples += 1

            # Extract data from saved record
            post_id = example.get("post_id")
            issue = example.get("issue", "")

            # For multi-round evaluations, use the original argument for semantic similarity
            # The "argument" field contains the previous round's edited version
            # The "original_argument" field (if present) contains the true original
            is_multi_round = example.get("metadata", {}).get("is_multi_round", False)
            if is_multi_round and "original_argument" in example:
                # Use previous round's output for generating new edits (already in "argument")
                argument_for_edits = example.get("argument", "")
                # Use true original for semantic similarity comparisons
                argument = example.get("original_argument", "")
                logger.info(f"Multi-round example detected: using original_argument for similarity comparisons")
            else:
                # Single round: argument is the original
                argument = example.get("argument", "")
                argument_for_edits = argument

            sentences = example.get("sentences", [])
            completion = example.get("completion", "")
            all_edits = example.get("edits", [])

            # Check if this is parse_diff mode from metadata
            is_parse_diff = example.get("metadata", {}).get("is_parse_diff", False)

            # Score each edit
            scored_edits = []
            # Use argument_for_edits for scoring (the text that was actually edited)
            baseline_cls_scores = appropriateness_scorer.get_appropriateness_scores(argument_for_edits) if appropriateness_scorer else {}

            for idx_edit, edit in enumerate(all_edits):
                logger.info(f"Scoring edit {idx_edit + 1}/{len(all_edits)}: {edit}")

                sentence_id = edit.get("sentence_id", 0)

                # Use original_sentence from the edit if available (for parse_diff mode)
                # Otherwise fall back to sentences array (for model-generated edits)
                original_sentence = edit.get("original_sentence")
                if not original_sentence:
                    try:
                        original_sentence = sentences[sentence_id - 1] if 0 < sentence_id <= len(sentences) else None
                    except (IndexError, TypeError):
                        original_sentence = None

                scored_edit = score_edit(
                    argument_for_edits,
                    edit,
                    baseline_scores=baseline_cls_scores,
                    original_sentence_context=original_sentence,
                    semantic_similarity_scorer=semantic_similarity_scorer,
                    fluency_scorer=fluency_scorer,
                    human_like_scorer=human_like_scorer,
                    appropriateness_scorer=appropriateness_scorer
                )
                scored_edit['original_sentence'] = original_sentence or ""
                scored_edit['sentence_id'] = sentence_id
                scored_edits.append(scored_edit)

            logger.info(f"Scored {len(scored_edits)} edits")

            # Collect statistics
            valid_count = sum(1 for e in scored_edits if e.get("valid"))
            perfect_ones = sum(1 for e in scored_edits if e.get("rewards", {}).get("perfect") == 1.0)
            reason_correct_count = sum(1 for e in scored_edits if e.get("reason_correct"))
            reason_correct_relaxed_count = sum(1 for e in scored_edits if e.get("reason_correct_relaxed"))

            total_edits += len(scored_edits)
            total_valid_edits += valid_count
            total_perfect_reward_ones += perfect_ones
            total_reason_correct += reason_correct_count
            total_reason_correct_relaxed += reason_correct_relaxed_count

            # Track invalid edit reasons
            for e in scored_edits:
                if not e.get("valid"):
                    edit_data = all_edits[scored_edits.index(e)]
                    reason = edit_data.get("reason")
                    inappropriate_part = edit_data.get("inappropriate_part")
                    rewritten_part = edit_data.get("rewritten_part")
                    original_sentence = e.get('original_sentence', '')

                    # Match the exact validation logic from score_edit
                    edit_context = original_sentence if original_sentence else argument_for_edits
                    has_reason = bool(reason)
                    has_at_least_one = bool(inappropriate_part) or bool(rewritten_part)
                    substring_match = (not inappropriate_part) or (inappropriate_part in edit_context)

                    if not has_reason:
                        invalid_reasons['no_reason'] += 1
                    elif not has_at_least_one:
                        invalid_reasons['no_content'] += 1
                    elif not substring_match:
                        invalid_reasons['substring_mismatch'] += 1

                # Track why valid edits are not perfect
                elif e.get("valid") and e.get("rewards", {}).get("perfect") != 1.0:
                    rewards = e.get("rewards", {})
                    ss = rewards.get("semantic_similarity", 0.0)
                    fluency = rewards.get("fluency", 0.0)
                    human_like = rewards.get("human_like", 0.0)

                    # Count which scorers failed
                    failed_scorers = []
                    if semantic_similarity_scorer and ss != 1.0:
                        failed_scorers.append('semantic_similarity')
                        total_scorer_failures['semantic_similarity'] += 1
                    if fluency_scorer and fluency != 1.0:
                        failed_scorers.append('fluency')
                        total_scorer_failures['fluency'] += 1
                    if human_like_scorer and human_like != 1.0:
                        failed_scorers.append('human_like')
                        total_scorer_failures['human_like'] += 1

                    if len(failed_scorers) > 1:
                        imperfect_reasons['multiple_failed'] += 1
                    elif 'semantic_similarity' in failed_scorers:
                        imperfect_reasons['semantic_similarity_failed'] += 1
                    elif 'fluency' in failed_scorers:
                        imperfect_reasons['fluency_failed'] += 1
                    elif 'human_like' in failed_scorers:
                        imperfect_reasons['human_like_failed'] += 1

            # Build argument after applying perfect edits
            # Apply to argument_for_edits (the text that was actually edited)
            perfect_edits = [
                {
                    'original_sentence': e.get('original_sentence', ''),
                    'inappropriate_part': e.get('inappropriate_part'),
                    'rewritten_part': e.get('rewritten_part')
                }
                for e in scored_edits
                if e.get("rewards", {}).get("perfect") == 1.0
            ]
            argument_after_edits = apply_edits_to_argument(perfect_edits, sentences, argument_for_edits)

            # Build argument after applying all valid edits
            all_valid_edits = [
                {
                    'original_sentence': e.get('original_sentence', ''),
                    'inappropriate_part': e.get('inappropriate_part'),
                    'rewritten_part': e.get('rewritten_part')
                }
                for e in scored_edits
                if e.get("valid") == True
            ]
            argument_after_all_edits = apply_edits_to_argument(all_valid_edits, sentences, argument_for_edits)

            # Argument-level classifier metrics
            # For multi-round: compare appropriateness of current round vs original
            # "scores_before" should be the original argument (what we're trying to improve)
            # "scores_after" should be the result of applying edits
            scores_before = appropriateness_scorer.get_appropriateness_scores(argument) if appropriateness_scorer else {}
            scores_after = appropriateness_scorer.get_appropriateness_scores(argument_after_edits) if appropriateness_scorer else {}
            scores_after_all = appropriateness_scorer.get_appropriateness_scores(argument_after_all_edits) if appropriateness_scorer else {}

            # Track flips per dimension
            flipped = False
            for dim in _ANALYSIS_DIMS:
                before_val = scores_before.get(dim)
                after_val = scores_after.get(dim)
                if before_val is not None and after_val is not None and after_val < 0.5:
                    flips_per_dim[dim] += 1
                    if dim == "Inappropriateness":
                        flipped = True

            flipped_all = False
            for dim in _ANALYSIS_DIMS:
                before_val = scores_before.get(dim)
                after_val_all = scores_after_all.get(dim)
                if before_val is not None and after_val_all is not None and after_val_all < 0.5:
                    if dim == "Inappropriateness":
                        flipped_all = True

            # Calculate metrics using MetricsCalculator (Sim, NES, PPL, App)
            # For parse_diff mode:
            #   - Perfect edits: Apply the edits (to measure quality of edits that pass scorers)
            #   - All valid edits: Use completion (ground truth human edit)
            if is_parse_diff:
                argument_after_edits_text = argument_after_edits  # Apply perfect edits
                argument_after_all_edits_text = completion  # Use ground truth for all edits
                logger.info("Parse_diff mode: using applied perfect edits and completion for all edits")
            else:
                # Use reconstructed arguments for model-generated edits
                argument_after_edits_text = argument_after_edits
                argument_after_all_edits_text = argument_after_all_edits

            # Debug logging
            logger.info(f"Metrics input - argument: {argument[:100]}...")
            logger.info(f"Metrics input - argument_after_edits_text: {argument_after_edits_text[:100]}...")

            # For perfect edits
            try:
                # calculate_metrics(x, y): x=predictions/edited, y=prompts/original
                # Swapped: x gets classified, y is reference for similarity/NES
                metrics_perfect = metrics_calculator.calculate_metrics(
                    [argument_after_edits_text],
                    [argument]
                )
                sim_score = float(metrics_perfect.get('mean_semantic_similarity', 0.0))
                nes_score = float(metrics_perfect.get('mean_token_edit_distance', 0.0))
                # Use prompt_perplexities (computed on x=edited text)
                ppl_score = float(metrics_perfect.get('prompt_perplexities', [float("inf")])[0])
                # Use classifier_predictions_app (probability of appropriate class on x=edited text)
                app_score = float(metrics_perfect.get('classifier_predictions_app', [0.0])[0])
            except Exception as e:
                logger.error(f"Failed to calculate metrics for perfect edits: {e}")
                sim_score = 0.0
                nes_score = 0.0
                ppl_score = float("inf")
                app_score = 0.0

            # For all valid edits
            try:
                # calculate_metrics(x, y): x=predictions/edited, y=prompts/original
                # Swapped: x gets classified, y is reference for similarity/NES
                metrics_all = metrics_calculator.calculate_metrics(
                    [argument_after_all_edits_text],
                    [argument]
                )
                sim_score_all = float(metrics_all.get('mean_semantic_similarity', 0.0))
                nes_score_all = float(metrics_all.get('mean_token_edit_distance', 0.0))
                # Use prompt_perplexities (computed on x=edited text)
                ppl_score_all = float(metrics_all.get('prompt_perplexities', [float("inf")])[0])
                # Use classifier_predictions_app (probability of appropriate class on x=edited text)
                app_score_all = float(metrics_all.get('classifier_predictions_app', [0.0])[0])
            except Exception as e:
                logger.error(f"Failed to calculate metrics for all valid edits: {e}")
                sim_score_all = 0.0
                nes_score_all = 0.0
                ppl_score_all = float("inf")
                app_score_all = 1.0

            # Binary appropriateness flags (GM will be computed in interface from aggregated values)
            app_bin = 1.0 if flipped else 0.0
            app_bin_all = 1.0 if flipped_all else 0.0

            # Global scorer metrics (perfect edits)
            global_ss_binary, global_ss_score = 0.0, 0.0
            global_hl_score = 0.0  # V2 returns proportion of sentences passing (0.0 to 1.0)
            global_fluency_binary, global_fluency_confidence = 0.0, 0.0

            try:
                global_ss_binary, global_ss_score = global_semantic_similarity_scorer.calculate_global_semantic_similarity(
                    argument, argument_after_edits
                )
            except Exception as e:
                logger.error(f"Global semantic similarity (perfect) failed: {e}")

            try:
                # Group perfect edits by sentence for V2 scorer
                perfect_edits_by_sentence = _group_edits_by_sentence(perfect_edits)
                global_hl_score = global_human_like_scorer.calculate_global_human_likeness(
                    argument, perfect_edits_by_sentence
                )
            except Exception as e:
                logger.error(f"Global human-likeness (perfect) failed: {e}")

            try:
                global_fluency_binary, global_fluency_confidence = global_fluency_scorer.calculate_global_fluency(
                    argument, argument_after_edits
                )
            except Exception as e:
                logger.error(f"Global fluency (perfect) failed: {e}")

            # Global scorer metrics (all valid edits)
            global_ss_binary_all, global_ss_score_all = 0.0, 0.0
            global_hl_score_all = 0.0  # V2 returns proportion of sentences passing (0.0 to 1.0)
            global_fluency_binary_all, global_fluency_confidence_all = 0.0, 0.0

            try:
                global_ss_binary_all, global_ss_score_all = global_semantic_similarity_scorer.calculate_global_semantic_similarity(
                    argument, argument_after_all_edits
                )
            except Exception as e:
                logger.error(f"Global semantic similarity (all) failed: {e}")

            try:
                # Group all valid edits by sentence for V2 scorer
                all_valid_edits_by_sentence = _group_edits_by_sentence(all_valid_edits)
                global_hl_score_all = global_human_like_scorer.calculate_global_human_likeness(
                    argument, all_valid_edits_by_sentence
                )
            except Exception as e:
                logger.error(f"Global human-likeness (all) failed: {e}")

            try:
                global_fluency_binary_all, global_fluency_confidence_all = global_fluency_scorer.calculate_global_fluency(
                    argument, argument_after_all_edits
                )
            except Exception as e:
                logger.error(f"Global fluency (all) failed: {e}")

            # Predicted scores
            pred_scores_before: Dict[str, float] = {}
            pred_scores_after: Dict[str, float] = {}
            pred_scores_after_all: Dict[str, float] = {}

            for dim in _ANALYSIS_DIMS:
                val_before = scores_before.get(dim)
                if val_before is not None:
                    pred_scores_before[dim] = 1.0 if float(val_before) >= 0.5 else 0.0

                val_after = scores_after.get(dim)
                if val_after is not None:
                    pred_scores_after[dim] = 1.0 if float(val_after) >= 0.5 else 0.0

                val_after_all = scores_after_all.get(dim)
                if val_after_all is not None:
                    pred_scores_after_all[dim] = 1.0 if float(val_after_all) >= 0.5 else 0.0

            # Write output record
            record = {
                "post_id": post_id,
                "issue": issue,
                "argument": argument,
                "argument_after_edits": argument_after_edits,
                "argument_after_all_edits": argument_after_all_edits,
                "metrics": {
                    "App": app_score,  # Use classifier probability of appropriate class
                    "Sim": sim_score,
                    "NES": nes_score,
                    "PPL": ppl_score,
                },
                "metrics_all": {
                    "App": app_score_all,  # Use classifier probability of appropriate class
                    "Sim": sim_score_all,
                    "NES": nes_score_all,
                    "PPL": ppl_score_all,
                },
                "global_scores": {
                    "semantic_similarity_binary": global_ss_binary,
                    "semantic_similarity_score": global_ss_score,
                    "human_like_score": global_hl_score,  # V2: proportion of sentences passing (0.0 to 1.0)
                    "fluency_binary": global_fluency_binary,
                    "fluency_confidence": global_fluency_confidence,
                },
                "global_scores_all": {
                    "semantic_similarity_binary": global_ss_binary_all,
                    "semantic_similarity_score": global_ss_score_all,
                    "human_like_score": global_hl_score_all,  # V2: proportion of sentences passing (0.0 to 1.0)
                    "fluency_binary": global_fluency_binary_all,
                    "fluency_confidence": global_fluency_confidence_all,
                },
                "predicted_scores_before": pred_scores_before,
                "predicted_scores_after": pred_scores_after,
                "predicted_scores_after_all": pred_scores_after_all,
                "edits": scored_edits,
            }
            f_out.write(json.dumps(record, ensure_ascii=False) + "\n")

            # Progress logging
            if idx < 3 or (idx + 1) % 50 == 0 or (idx + 1) == num_examples:
                elapsed = time.time() - example_start
                logger.info(
                    f"[{idx + 1}/?] eval={elapsed:.1f}s edits={len(scored_edits)} valid={valid_count} perfect={perfect_ones}"
                )

    # Compute flip percentages
    flip_percentages = {dim: (flips_per_dim[dim] / max(1, num_examples)) for dim in _ANALYSIS_DIMS}

    logger.info(
        f"Finished. Time={time.time() - start_all:.1f}s | examples={num_examples}"
        f" | edits={total_edits} valid_edits={total_valid_edits} perfect={total_perfect_reward_ones}"
        f" | reason_correct={total_reason_correct} ({total_reason_correct / max(1, total_edits):.1%})"
        f" | reason_correct_relaxed={total_reason_correct_relaxed} ({total_reason_correct_relaxed / max(1, total_edits):.1%})"
        f" | App%={flip_percentages.get('Inappropriateness', 0.0):.2%}"
    )

    # Log invalid edit breakdown
    total_invalid = total_edits - total_valid_edits
    if total_invalid > 0:
        logger.info(f"Invalid edit breakdown ({total_invalid} total invalid):")
        logger.info(f"  - no_reason: {invalid_reasons['no_reason']} ({invalid_reasons['no_reason'] / total_invalid:.1%})")
        logger.info(f"  - no_content: {invalid_reasons['no_content']} ({invalid_reasons['no_content'] / total_invalid:.1%})")
        logger.info(f"  - substring_mismatch: {invalid_reasons['substring_mismatch']} ({invalid_reasons['substring_mismatch'] / total_invalid:.1%})")

    # Log imperfect edit breakdown
    total_imperfect = total_valid_edits - total_perfect_reward_ones
    if total_imperfect > 0:
        logger.info(f"\nImperfect edit breakdown ({total_imperfect} valid but not perfect):")
        logger.info(f"  Single scorer failures:")
        logger.info(f"    - semantic_similarity_failed only: {imperfect_reasons['semantic_similarity_failed']} ({imperfect_reasons['semantic_similarity_failed'] / total_imperfect:.1%})")
        logger.info(f"    - fluency_failed only: {imperfect_reasons['fluency_failed']} ({imperfect_reasons['fluency_failed'] / total_imperfect:.1%})")
        logger.info(f"    - human_like_failed only: {imperfect_reasons['human_like_failed']} ({imperfect_reasons['human_like_failed'] / total_imperfect:.1%})")
        logger.info(f"  - multiple_failed: {imperfect_reasons['multiple_failed']} ({imperfect_reasons['multiple_failed'] / total_imperfect:.1%})")
        logger.info(f"\n  Total failures per scorer (including multiple):")
        logger.info(f"    - semantic_similarity: {total_scorer_failures['semantic_similarity']} ({total_scorer_failures['semantic_similarity'] / total_imperfect:.1%})")
        logger.info(f"    - fluency: {total_scorer_failures['fluency']} ({total_scorer_failures['fluency'] / total_imperfect:.1%})")
        logger.info(f"    - human_like: {total_scorer_failures['human_like']} ({total_scorer_failures['human_like'] / total_imperfect:.1%})")

    # Log per-dimension flip percentages
    logger.info("\nFlip percentages per dimension:")
    for dim in _ANALYSIS_DIMS:
        logger.info(f"- {dim}: {flip_percentages[dim]:.2%}")

    logger.info(f"Wrote {output_jsonl}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Evaluate edits with configurable scorers.")
    parser.add_argument("--input_jsonl", type=str, required=True, help="Path to input JSONL file with generated edits.")
    parser.add_argument("--output_jsonl", type=str, required=True, help="Path to output JSONL file with scored edits.")

    # Scorer toggles (thresholds are defined in scorer classes)
    parser.add_argument("--disable_semantic_similarity", action="store_true", help="Disable semantic similarity scorer.")
    parser.add_argument("--disable_fluency", action="store_true", help="Disable fluency scorer.")
    parser.add_argument("--disable_human_like", action="store_true", help="Disable human-like scorer.")
    parser.add_argument("--disable_appropriateness", action="store_true", help="Disable appropriateness scorer.")
    parser.add_argument("--weave_project", type=str, default=None, help="Weave project name for tracing (e.g., 'username/project-name'). If not provided, Weave tracing is disabled.")

    args = parser.parse_args()

    main(
        args.input_jsonl,
        args.output_jsonl,
        disable_semantic_similarity=args.disable_semantic_similarity,
        disable_fluency=args.disable_fluency,
        disable_human_like=args.disable_human_like,
        disable_appropriateness=args.disable_appropriateness,
        weave_project=args.weave_project,
    )
